# Creates release.
name: Create Release
run-name: Create Release of ${{ github.ref_name }}

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'liberica'
        cache: maven
    - name: Build with Maven
      run: |
        mvn --batch-mode clean
        mvn --batch-mode release:prepare --file pom.xml -DpushChanges=false
        mvn --batch-mode release:perform --file pom.xml -DlocalCheckout=true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Publish release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'      
      with:
        files: |
          target/checkout/safebox2kdbx/target/safebox2kdbx-*.jar 
